
language: python

python:
  - { PATH: "{{Python37}}", VERSION: 3.7, DIST: std, PYINT: python3.7, PYTHONPATH: src }
  - { PATH: "{{Python38}}", VERSION: 3.8, DIST: std, PYINT: python3.8, PYTHONPATH: src }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - if [[ -d "/var/lib/jenkins/.local/lib" ]]; then rm -r -f /var/lib/jenkins/.local/lib; fi
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --no-cache-dir --upgrade --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT --version
  - $PYINT -m pip freeze

script:
  - { CMD: "$PYINT -u setup.py unittests", NAME: "UT" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*LONG.*\" -g \".*chrome.*\"", NAME: "UT_LONG" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*chrome.*\"", NAME: "UT_LONG_CHROME" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*base.*\" -g \".*datascientist.*\"", NAME: "UT_SKIP_BASE", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*sqlitespy.*\"", NAME: "UT_SKIP_SQLLITE", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*pywin32.*\"", NAME: "UT_SKIP_PYWIN32", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*minimal.*\"", NAME: "UT_SKIP_MINIMAL", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*pyquickhelper.*\"", NAME: "UT_SKIP_PYQUICKHELPER", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*pyensae.*\"", NAME: "UT_SKIP_PYENSAE", TIMEOUT: 7200 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*datascientist.*\"", NAME: "UT_SKIP_DATASCIENTIST", TIMEOUT: 10000 }
  - { CMD: "$PYINT -u setup.py unittests -e \".*SKIP.*notebook.*\"", NAME: "UT_SKIP_NB" }

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.7" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
