"""
@file
@brief Missing information about licenses
"""

missing_module_licenses = {
    "xgboost": "Apache-2",
    "actuariat_python": "MIT",
    "code_beatrix": "MIT",
    "ensae_teaching_cs": "MIT",
    "pymyinstall": "MIT",
    "pyensae": "MIT",
    "pyquickhelper": "MIT",
    "pymmails": "MIT",
    "pyrsslocal": "MIT",
    "pysqllike": "MIT",
    "spyre": "MIT",
    "dataspyre": "MIT",
    "ete": "GNU v3",
    "ete3": "GNU v3",
    "datrie": "LGPL v2.1",
    "blaze": "BSD",
    "glueviz": "BSD",
    "h5py": "BSD",
    "statsmodels": "BSD",
    "toolz": "BSD",
    "trackpy": "BSD - 3 clauses",
    "jupyter_core": "BSD",
    "jupyter_client": "BSD",
    "metakernel": "BSD",
    "scilab_kernel": "BSD",
    "pyexecjs": "MIT",
    "selenium": "Apache Software License",
    "alabaster": "BSD",
    "cloud_sptheme": "BSD",
    "colorama": "BSD",
    "guzzle_sphinx_theme": "BSD~MIT",
    "itcase_sphinx_theme": "no license",
    "pypiserver": "BSD",
    "solar_theme": "BSD~MIT",
    "sphinx_bootstrap_theme": "MIT",
    "sphinx_py3doc_enhanced_theme": "BSD",
    "sphinx_readable_theme": "MIT",
    "sphinxjp.themes.basicstrap": "MIT",
    "sphinxjp.themes.sphinxjp": "MIT",
    "wild_sphinx_theme": "BSD",
    "SQLAlchemy": "MIT",
    "graphviz": "MIT",
    "anyjson": "BSD",
    "brewer2mpl ": "MIT",
    "cached_property": "BSD",
    "celery": "BSD",
    "colorspacious": "MIT",
    "cgal_bindings": "Boost Software License 1.0",
    "Cython": "Apache Software License",
    "datashape": "BSD",
    "cubehelix": "~BSD - 2 clauses",
    "dbfread": "MIT",
    "dynd": "BSD",
    "fabric": "BSD",
    "feedparser": "~BSD - 2 clauses",
    "gmpy2": "LGPLv3+",
    "itsdangerous": "BSD",
    "kombu": "BSD",
    "la": "BSD",
    "lifelines": "MIT",
    "line_profiler": "BSD",
    "lxml": "BSD",
    "Mako": "MIT",
    "marisa_trie": "MIT",
    "mock": "BSD",
    "msgpack-python": "Apache Software License",
    "multimethods": "MIT",
    "multipledispatch": "BSD",
    "nodeenv": "BSD",
    "oauthlib": "BSD",
    "patsy": "BSD",
    "pbr": "Apache Software License",
    "pims": "~BSD",
    "pipdeptree": "MIT",
    "PyAudio": "MIT",
    "pycrypto": "Public Domain + patent for some algorithm, check https://github.com/dlitz/pycrypto/tree/master/LEGAL",
    "planar": "BSD",
    "pygal_maps_world": "LGPLv3+",
    "pymesos": "BSD",
    "pystache": "MIT",
    "pytz": "MIT",
    "requests_oauthlib": "ISC",
    "rope_py3k": "GPL=OpenBSD",
    "smart_open": "Public Domain",
    "sphinxjp.themes.revealjs": "MIT",
    "textblob": "MIT",
    "tzlocal": "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "viscm": "MIT",
    "zs": "BSD",
    "neural-python": "MIT",
    "dask": "BSD",
    "NLopt": "LGPL",
    "ipython_genutils": "BSD",
    "memory_profiler": "BSD",
    "snakeviz": "BSD",
    "ansi2html": "GPLv3+",
    "brewer2mpl": "MIT",
    "dev": "Public Domain",
    "django-model-utils": "BSD",
    "django-userena": "BSD",
    "django-uuidfield": "~BSD",
    "easy-thumbnails": "BSD",
    "gunicorn": "MIT",
    "lockfile": "MIT",
    "gevent": "MIT",
    "lz4": "BSD",
    "opencv_python": "BSD",
    "ptyprocess": "ISC",
    "terminado": "BSD",
    "easy_thumbnails": "BSD",
    "llvmpy": "BSD",
    "pysterior": "MIT",
    "pymc3": "Apache-2",
    "tqdm": "MIT",
    "pandas-highcharts": "MIT",
    "holoviews": "BSD",
    "Bottleneck": "Simplified BSD",
    "cyordereddict": "MIT",
    "future": "MIT",
    "python-gmaps": "BSD",
    "libpython": "Python",
}
